### ISSUE TITLE
Female prayer area

### ISSUE THREAD

**Issue by Sahad30** [kamranmuazzam/imc_demands#3] opened 2024-08-21 17:48 UTC
Even though there are many empty spaces within the compound yet it is not allocated and female students often miss their dhur prayer

**Comment by kamranmuazzam** [comment] 2024-08-21 17:55
duplicate of #2

**Comment by kamranmuazzam** [comment] 2024-08-21 17:56
closed as duplicate of #2

**Closed as not planned by kamranmuazzam** 2024-08-21 17:56 UTC
Labels: duplicate, demands
